version: '3.3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: adrianowead/php80-apache2-ubuntu20-04
    container_name: php80-apache2-ubuntu20-04
    ports:
      - '8080:80'
    volumes:
      - './src:/var/www/html'